// apps/backend/services/mistralGenerate.mjs
import fetch from "node-fetch";
// backend call the mistral API

/**
 * Call local Mistral via Ollama to generate release notes
 * using ONLY commit messages (best performance)
 */
export async function mistralGenerate({ commits, version, prompt }) {
  //this function takes c,v,p to generate rn 
  const changelog = commits //convert commit array to text
    .map(
      (c) =>
        `- ${c.message} (by @${c.author_name || "unknown"})` // turn commit --> bullet line
    )
    .join("\n");

    //send to an llm

  const finalPrompt = `
You are an expert technical writer for Visual Studio Code, responsible for generating official, professional release notes. Your goal is to convert granular commit data into a high-level, benefit-driven narrative, mirroring the style and structure of the official VS Code Update pages.

### Task
Generate a polished, narrative-style release notes document based ONLY on the provided commit messages. **Do not use the standard Added/Changed/Fixed structure.** Instead, group related changes into logical, user-facing feature sections.

### Version:
${version || "Unspecified"}

### Source Data (Commits to Analyze):
${changelog}

### User Goal:
${prompt || "Generate high-quality release notes that focus on user benefits and major features."}

### Target Output Style (Mimic Official VS Code Updates):
1.  **Start with a strong welcome and a bulleted list of Key Highlights.** These highlights must be the 8-12 most impactful features/fixes derived from the commits.
2.  **Organize the body of the document into major thematic Headings** (e.g., "GitHub Copilot," "Workbench," "Accessibility," "Terminal," "Languages").
3.  **Under each thematic heading, write narrative paragraphs and/or use bullet points** to describe the new features and improvements. Focus on *what the user gains* (the benefit), not the commit details or internal issue numbers.
4.  **Conclude with a final section for "Engineering" or "Notable Fixes"** for important, high-impact fixes that don't fit into a main feature section.

### Output Structure:
Please begin with the main body content, ensuring a clean and professional tone.

<Start Document Here>
`;

  console.log("\n Sending to Mistral…");
//We send the prompt to our local Mistral model running through Ollama.
  const response = await fetch("http://127.0.0.1:11434/api/generate", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model: "mistral",
      prompt: finalPrompt,
      stream: false
    })
  });

  if (!response.ok) {
    throw new Error(`Mistral request failed: ${response.status}`);
  }
//parse the JSON returned by the model
  const data = await response.json();
//final release notes string generated by the model.”
  return (data?.response || "").trim();
}
